version: "3"

services:
  frontend-app:
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - "8080:80"
    depends_on:
      - backend-app

  backend-app:
    build:
      context: ./backend
      dockerfile: ./Dockerfile
    env_file:
      - path: ./.env
        required: true
    ports:
      - "3000:3000"
    depends_on:
      - surrealdb
    networks:
      - backend

  surrealdb:
    image: surrealdb/surrealdb:latest
    command: start --log trace --auth --user root --pass root
    expose:
      - "8000"
    restart: always
    networks:
      - backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    command: --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yaml
    depends_on:
      - backend-app
    networks:
      - backend

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "4000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    depends_on:
      - prometheus
    networks:
      - backend

networks:
  backend:
