apiVersion: apps/v1
kind: Deployment
metadata:
  name: surrealdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: surrealdb
  template:
    metadata:
      labels:
        app: surrealdb
    spec:
      containers:
        - name: surrealdb
          image: surrealdb/surrealdb:latest
          args:
            [
              "start",
              "--log",
              "trace",
              "--auth",
              "--user",
              "root",
              "--pass",
              "root",
            ]
          ports:
            - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: surrealdb
spec:
  selector:
    app: surrealdb
  ports:
    - port: 8000
      targetPort: 8000
