name: Backend CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

  steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Install rust toolchain
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        override: true
        components: rustfmt, clippy

    - name: Start SurrealDB
      run: |
        docker run -d --rm --pull always -p 8000:8000 \
        surrealdb/surrealdb:latest start --log trace --auth --user root --pass root

    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          target
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

    - name: Run cargo fmt
      uses: actions-rs/cargo@v1
      with:
        command: fmt
        args: --all -- --check

    - name: Run cargo check
      uses: actions-rs/cargo@v1
      with:
        command: check

    - name: Run cargo clippy
      uses: actions-rs/cargo@v1
      with:
        command: clippy
        args: -- -D warnings

    - name: Run cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
